version: '3.3'
services:
    maubot:
        restart: unless-stopped
        ports:
            - '8080:29316'
        volumes:
            - '$PWD:/data:z'
        image: 'dock.mau.dev/maubot/maubot:latest'
